### ISSUE TITLE
Add `open` and `close` command functionality

### ISSUE THREAD

**Issue by Sawtaytoes** [dsandor/fauxmojs#10]
For whatever reason, when using [FauxMo for the ESP8266](https://bitbucket.org/xoseperez/fauxmoesp), I'm able to use the commands `open` and `close` instead of just `on` and `off`. Is it possible to add these commands as well to fauxmojs?

**Comment by dsandor** [comment]
@Sawtaytoes can you share a code snippet?

**Comment by dsandor** [comment]
It looks like that project is using a different base hardware to emulate.  As discussed in issue #18 we will add other hardware profiles to support more feature rich hardware.
