### ISSUE TITLE
Release/publish new package on NPM

### ISSUE THREAD

**Issue by maxwroc** [dsandor/fauxmojs#14]
Can you please publish new updated package on NPM with the last fix: https://github.com/dsandor/fauxmojs/commit/c82edac4bbab5f43cca69f2553109c20b8e60cf6

Thanks in advance!
Maks

**Comment by dsandor** [comment]
Terribly sorry for the delay.  Life got in the way.  Published `fauxmojs@1.0.2`.  Also note you can add the master branch to your package.json by way of git.
