### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by bwired-nl** [dsandor/fauxmojs#20]
Hi
im getting this

/home/knu/bwired/alexa/node_modules/fauxmojs/lib/index.js:11
  constructor(options = {}) {
                                  ^

SyntaxError: Unexpected token =

is it my node version?
4.2.6

**Comment by bwired-nl** [comment]
solved with using latest node version

**Comment by dsandor** [comment]
We should update the readme and package.json to reflect the minimum nodejs requirements.
