### ISSUE TITLE
each device executed during discovery

### ISSUE THREAD

**Issue by johngo7470** [dsandor/fauxmojs#26]
Is there a way to differentiate between the callback function being triggered by Device Discovery and calling the function from a voice command? When I ask Alexa to discover all devices, it actually triggers each device to operate as if it were called with an "on".  This is a bit of a problem, because it is activating devices, that I don't want activated during discovery.

**Comment by boeserwolf** [comment]
You could use my PR from 2017 which solves the issue by handling the status queries and caching the last known device states:

https://github.com/boeserwolf/fauxmojs

**Comment by johngo7470** [comment]
Thank you for your reply. 

For reasons unknown, my configuration went haywire over the summer, and all devices were constantly activating, even though nothing was being called.  I resolved it by switching to fauxmo, so I never did figure out what went wrong with my implementation of fauxmojs.
